default: &default
  adapter: postgresql
  encoding: unicode
  username: root
  password: '123456'
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #port: 5432

development:
  <<: *default
  database: notebook_development

test:
  <<: *default
  database: notebook_test

production:
  <<: *default
  database: notebook_production
  username: notebook
  password: <%= ENV['NOTEBOOK_DATABASE_PASSWORD'] %>
